main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    # signup url
    path('accounts/signup/', views.signup, name='signup'),
    path('destinations/<int:destination_id>/', views.destination_details, name='detail'),
    path('destinations/create/', views.DestinationCreate.as_view(), name='destinations_create'),
    path('destinations/<int:pk>/update/', views.DestinationUpdate.as_view(), name='destinations_update'),
    path('destinations/<int:pk>/delete/', views.DestinationDelete.as_view(), name='destinations_delete'),
    path('destinations/<int:destination_id>/add_comment/', views.add_comment, name='add_comment'),
    path('comments/<int:pk>/update', views.CommentUpdate.as_view(), name='comments_update'),
    path('destinations/<int:pk>/comment_delete', views.CommentDelete.as_view(), name='comments_delete'),
    path('user/<int:user_id>', views.user_index, name='user_index'),
    path('destinations/<int:destination_id>/add_photo', views.add_photo, name='add_photo'),
]

nomadland/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Destination(models.Model):
  place = models.CharField(max_length=100)
  description = models.TextField(max_length=300)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.place}"

  def get_absolute_url(self):
    return reverse('detail', kwargs={'destination_id': self.id})

class Photo(models.Model):
  url = models.CharField(max_length=200)
  destination = models.ForeignKey(Destination, on_delete=models.CASCADE)

  def __str__(self):
    return f"Photo for destination_id: {self.destination_id} @ {self.url}"

class Comment(models.Model):
  text = models.TextField(max_length=250)
  destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def get_absolute_url(self):
    return reverse('detail', kwargs={'destination_id': self.destination.id})

main_app/forms.py
from django.forms import ModelForm
from .models import Comment

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

main_app/views.py
import os
import uuid
import boto3
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login
from django.urls import reverse, reverse_lazy
from .models import Destination, Comment, User, Photo
from .forms import CommentForm


# Create your views here.
def home(request):
    destinations = Destination.objects.all().order_by('-id')
    return render(request, 'home.html', { 'destinations': destinations })

def destination_details(request, destination_id):
  destination = Destination.objects.get(id=destination_id)
  comment_form = CommentForm()
  comments = Comment.objects.filter(destination=destination_id)
  if Photo.objects.filter(destination=destination_id).exists():
    photo = Photo.objects.get(destination=destination_id)
  else:
    photo = None
  return render(request, 'destinations/detail.html', {
    'destination': destination, 
    'comment_form': comment_form,
    'comments': comments,
    'photo': photo
    })

class DestinationUpdate(LoginRequiredMixin, UpdateView):
  model = Destination
  fields = ['description']

class DestinationDelete(LoginRequiredMixin, DeleteView):
  model = Destination
  success_url = '/'

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # Save the user to the db
      user = form.save()
      # automatically login new user
      login(request, user)
      return redirect('home')
    else:
      error_message = 'Invalid sign-up. Try again.'
  # A bad POST or GET request, so render signup template
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class DestinationCreate(LoginRequiredMixin, CreateView):
  model = Destination
  fields = ['place', 'description']

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)


# class CommentCreate(CreateView):
#   model = Comment
#   fields = ['text']
  
#   def form_valid(self, form, destination_id):
#     form.instance.user = self.request.user
#     form.instance.destination = destination_id
#     return super().form_valid(form)

@login_required
def add_comment(request, destination_id):
  form = CommentForm(request.POST)
  if form.is_valid():
    new_comment = form.save(commit=False)
    new_comment.destination_id = destination_id
    new_comment.user_id = request.user.id
    new_comment.save()
  return redirect('detail', destination_id=destination_id)

class CommentUpdate(LoginRequiredMixin, UpdateView):
  model = Comment
  fields = ['text']

class CommentDelete(LoginRequiredMixin, DeleteView):
  model = Comment
  #success_url = 'destination/<int:destination_id>'
  def get_success_url(self):
    #destination_id = self.destination.id
    return f"/destinations/{self.object.destination.id}"

@login_required
def user_index(request, user_id):
  user_id = request.user.id
  user = User.objects.get(id=user_id)
  return render(request, 'user.html', {'user': user})

@login_required
def add_photo(request, destination_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      bucket = os.environ['S3_BUCKET']
      s3.upload_fileobj(photo_file, bucket, key)
      url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
      Photo.objects.create(url=url, destination_id=destination_id)
    except Exception as e:
      print('An error occrued uploading file to S3')
      print(e)
  return redirect('detail', destination_id=destination_id)

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'images/favicon.png' %}"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
      rel="stylesheet"
    />
    <title>NomandLand</title>
  </head>
  <body class="dark-mode">
    <section class="modal hidden sm-container">
      <div class="flex-jc-sb">
        <h2 class="md-txt txt-subtle">Navigation</h2>
        <button class="btn outlined" id="btn-close">
          <i class="ri-close-line"></i>
        </button>
      </div>
      <div class="sm-spacer"></div>
      <ul class="flex-col">
        {% if user.is_authenticated %}
        <li class="nav-link">
          <a href="{% url 'destinations_create' %}">Add Destination</a>
        </li>
        <div class="xs-spacer"></div>
        <li class="nav-link"><a href="{% url 'logout' %}">Logout</a></li>
        <div class="xs-spacer"></div>
        <li class="nav-link">
          <a href="{% url 'user_index' user.id %}">Profile</a>
        </li>
        {% else %}
        <li class="nav-ink"><a href="{% url 'login' %}">Login</a></li>
        <div class="xs-spacer"></div>
        <li class="nav-link"><a href="{% url 'signup' %}">Signup</a></li>
        {% endif %}
      </ul>
    </section>
    <div class="overlay hidden"></div>
    <header class="app-header flex-al-c">
      <nav class="container flex-jc-sb">
        <ul>
          <li class="logo">
            <a href="{% url 'home' %}"
              ><img
                src="{% static 'images/logo.png' %}"
                alt="website logo"
                id="logo"
            /></a>
          </li>
        </ul>
        <ul class="nav-links">
          {% if user.is_authenticated %}
          <li class="nav-link">
            <a href="{% url 'destinations_create' %}">Add Destination</a>
          </li>
          <li class="nav-link"><a href="{% url 'logout' %}">Logout</a></li>
          <li class="nav-link">
            <a href="{% url 'user_index' user.id %}"
              ><i class="ri-user-line lg-txt"></i
            ></a>
          </li>
          {% else %}
          <li class="btn"><a href="{% url 'login' %}">Login</a></li>
          <li class="btn outlined"><a href="{% url 'signup' %}">Signup</a></li>
          {% endif %}
        </ul>
        <button class="btn nav-btn outlined" id="btn-open"></button>
      </nav>
    </header>
    <div class="lg-spacer"></div>
    <main>{% block content %} {% endblock %}</main>
    <div class="md-spacer"></div>
    <footer>
      <div class="md-spacer"></div>
      <div class="container flex-jc-sb">
        <h3 class="txt-subtle xs-txt">
          All Rights Reserved, &copy; 2022 NomadLand &nbsp;
        </h3>
      </div>
      <div class="md-spacer"></div>
    </footer>
    <script>
      // const themeBtn = document.getElementById('theme-btn')
      // const logo = document.getElementById('logo')
      // const body = document.body
      // themeBtn.addEventListener('click', toggleTheme)
      // function toggleTheme() {
      //     if (body.classList.contains('dark-mode')) {
      //         body.classList.toggle('light-mode')
      //         logo.src =`{% static 'images/logo-2.png' %}`
      //         console.log(logo.src)
      //     } else if (body.classList.contains('light-mode')) {
      //         body.classList.toggle('dark-mode')
      //         logo.src = `{% static 'images/logo.png' %}`
      //         console.log(logo.src)
      //     }
      // }
      const modal = document.querySelector(".modal");
      const overlay = document.querySelector(".overlay");
      const openModalBtn = document.getElementById("btn-open");
      const closeModalBtn = document.getElementById("btn-close");

      const openModal = function () {
        modal.classList.remove("hidden");
        overlay.classList.remove("hidden");
      };

      openModalBtn.addEventListener("click", openModal);

      const closeModal = function () {
        modal.classList.add("hidden");
        overlay.classList.add("hidden");
      };

      closeModalBtn.addEventListener("click", closeModal);

      overlay.addEventListener("click", closeModal);
    </script>
  </body>
</html>

main_app/templates/destinations/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="flex-jc-sb">
    <section>
      <h1 class="lg-txt txt-focus">{{ destination.place }}</h1>
      <p class="txt-subtle sm-txt">Posted by {{ destination.user.username }}</p>
    </section>
    {% if destination.user.id == request.user.id %}
      <section>
        <a href="{% url 'destinations_update' destination.id %}" class="btn outlined"><i class="ri-edit-line"></i></a>
        <a href="{% url 'destinations_delete' destination.id %}" class="btn outlined"><i class="ri-delete-bin-7-line"></i></a> 
      </section>
    {% endif %}
  </div>
  <div class="xs-spacer txt-header-border"></div>
</div>
<div class="sm-spacer"></div>
  {% if photo %}
  <div class="container">
    <img src="{{ photo.url }}" alt="Destination Photo">
  </div>
  {% elif destination.user.id == request.user.id %}
    <form action="{% url 'add_photo' destination.id %}" enctype="multipart/form-data" method="POST"
    class="container form flex-col card" id="photo-form">
      {% csrf_token %}
      <h2 class="md-txt txt-subtle">Add Photo</h2>
      <div class="sm-spacer"></div>
      <div class="fields-container">
        <input type="file" name="photo-file" class="card xs-spacer">
      </div>
      <div class="xs-spacer"></div>
      <button type="submit" class="confirm btn">Submit</button>
    </form>
  {% endif %}
  <div class="sm-spacer"></div>
  <div class="md-container">
    <p>{{ destination.description }}</p>
  </div>
  <div class="md-spacer"></div>
<!-- comment section -->
<div class="container txt-header-border">
  <h2 class="md-txt txt-subtle">{{ comments.count }} Comments</h2>
  <div class="xs-spacer"></div>
</div>
{% if user.is_authenticated %}
  <form action="{% url 'add_comment' destination.id %}" method="POST" class="container">
    {% csrf_token %}
    <div class="sm-spacer"></div>
    <section class="flex-al-c fields-container">
      <i class="ri-user-line md-txt txt-subtle"></i>
      <input type="text" name="text" class="card xs-spacer" required>
    </section>
    <div class="xs-spacer"></div>
    <section class="fields-container flex-end">
      <button type="submit" class="confirm btn">Add comment</button>
    </section>
    <!-- {{ comment_form.as_p }} -->
  </form>
{% endif %}
<div class="sm-spacer"></div>
<section class="container">
  {% for comment in comments %}
    <div class="flex card xs-spacer">
      <div class="flex-col">
        <i class="ri-user-line md-txt txt-subtle"></i>
        <p class="xs-txt txt-subtle">{{ comment.user.username }}</p>
      </div>
      <div class="flex-al-c">
        <p class="sm-txt txt-focus" style="margin-left: 1rem;">{{ comment.text }}</p>
      </div>
    </div>
    <div class="xs-spacer"></div>
    {% if comment.user.id == request.user.id%}
    <section class="flex">
      <a href="{% url 'comments_update' comment.id %}" class="btn outlined"><i class="ri-edit-line"></i></a>
      <a href="{% url 'comments_delete' comment.id %}" class="btn outlined"><i class="ri-delete-bin-7-line"></i></a>
    </section>
    <div class="xs-spacer"></div>
    {% endif %}
  {% endfor %}
</section>
{% endblock %}

main_app/templates/home.html
{%  extends 'base.html' %}
{% block content %}
<div class="container">
  <h1 class="lg-txt txt-focus txt-header">Mission Statement</h1>
  <div class="xs-spacer"></div>
  <p class="txt-subtle sm-txt">
    A trusted platform for  Nomads and travelers
    to share their experiences around
    the world and learn about new travel destinations
    from other travelers.
  </p>
</div>
<div class="md-spacer"></div>
<div class="grid container">
  {% for destination in destinations %}
    <a href="{% url 'detail' destination.id %}">
      <div class="card main item flex-col sm-spacer">
        <i class="ri-leaf-line md-txt txt-subtle"></i>
        <div class="lg-spacer"></div>
        <div class="main-content">
          <h1 class="lg-txt txt-subtle">{{ destination.place }}</h1>
          <div class="xs-spacer"></div>
          <p class="txt-subtle sm-txt">Posted by {{ destination.user.username }}</p>
        </div>
      </div>
    </a>
  {% endfor %}
</div>
{% endblock %}

main_app/templates/main_app/comment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <form action="" method="POST" class="card form sm-container flex-col">
    {% csrf_token %}
    <h2 class="md-txt txt-focus">Delete Comment?</h2>
    <div class="md-spacer"></div>
    <section class="flex">
      <button type="submit" class="delete btn"><i class="ri-delete-bin-7-line"></i>Delete</button>
      <a href="{% url 'detail' comment.destination.id %}" class="btn outlined">Cancel</a>
    </section>
  </form>

{% endblock %}

main_app/templates/main_app/comment_form.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST" class="sm-container card form flex-col">
  <h2 class="md-txt txt-focus">Edit Comment</h2>
  <div class="md-spacer"></div>
  {% csrf_token %}
  <!-- {{ form.as_p }} -->
  <section class="fields-container">
    <textarea name="text" class="card xs-spacer">{{ object.text }}</textarea>
  </section>
  <div class="xs-spacer"></div>
  <section class="fields-container txt-subtle flex-col">
    <button class="confirm btn" type="submit">Edit Comment</button>
  </section>
</form>

{% endblock %}

main_app/templates/main_app/destination_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <form action="" method="POST" class="card form sm-container flex-col">
    {% csrf_token %}
    <h2 class="md-txt txt-focus">Delete {{ object.place }}?</h2>
    <div class="md-spacer"></div>
    <section class="flex">
      <button type="submit" class="delete btn"><i class="ri-delete-bin-7-line"></i>Delete</button>
      <a href="{% url 'detail' object.id %}" class="btn outlined">Cancel</a>
    </section>
  </form>
{% endblock %}

main_app/templates/main_app/destination_form.html
{% extends 'base.html' %}

{% block content %}

<form action="" class="sm-container form card flex-col" method="POST">
  {% csrf_token %}
  {% if object %}
    <h2 class="md-txt txt-focus">Edit {{ object.place }}</h2>
  {% else %}
    <h2 class="md-txt txt-focus">Add New Destination</h2>
  {% endif %}
  <div class="md-spacer"></div>
  <section class="fields-container txt-subtle flex-col">
    <label for="">Place</label>
    <div class="xs-spacer"></div>
    <input type="text" name="place" class="card xs-spacer" value="{{ object.place }}" required>
  </section>
  <div class="sm-spacer"></div>
  <section class="fields-container txt-subtle flex-col">
    <label for="">Description</label>
    <div class="xs-spacer"></div>
    <textarea name="description" class="card xs-spacer" required>{{ object.description }}</textarea>
  </section>
  <div class="xs-spacer"></div>
  <section class="fields-container txt-subtle flex-col">
    <button class="confirm btn" type="submit">Confirm</button>
  </section>
</form>

{% endblock %}

main_app/templates/user.html
{% extends 'base.html' %}

{% block content %}
<div class="card xs-container flex-col flex-al-c form">
  <i class="ri-user-line txt-focus lg-txt"></i>
  <div class="xs-spacer"></div>
  <h3 class="txt-focus md-txt">{{ user.username }}'s Profile</h3>
  <div class="sm-spacer"></div>
  <p class="txt-subtle sm-txt">{{ user.destination_set.count }} Posts</p>
</div>
<div class="md-spacer"></div>
{% if user.destination_set.count %}
<div class=" grid container">
  {% for destination in user.destination_set.all %}
    <!-- <a href="{% url 'detail' destination.id %}"><h1>{{ destination.place }}</h1></a> -->
    <a href="{% url 'detail' destination.id %}">
      <div class="card item flex-col sm-spacer">
        <i class="ri-leaf-line md-txt txt-subtle"></i>
        <div class="lg-spacer"></div>
        <div class="main-content">
          <h1 class="lg-txt txt-subtle">{{ destination.place }}</h1>
          <div class="xs-spacer"></div>
          <p class="txt-subtle">Posted by {{ destination.user.username }}</p>
        </div>
      </div>
    </a>
  {% endfor %}
</div>
{% else %}
  <div class="sm-container flex-col flex-al-c">
    <h2 class="lg-txt txt-subtle">No Posts.</h2>
  </div>
{% endif %}



{% endblock %}